"""sync award_letters schema

Revision ID: 3944ed371bb6
Revises: 8e3e38e38dc7
Create Date: 2026-05-20 19:05:56.169348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3944ed371bb6'
down_revision = '8e3e38e38dc7'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('award_letters', schema=None) as batch_op:

        # 1. Add new correct column
        batch_op.add_column(
            sa.Column('file_url', sa.String(length=255), nullable=True)
        )

        # 2. Stop enforcing old columns
        batch_op.alter_column('file_path', nullable=True)
        batch_op.alter_column('original_filename', nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award_letters', schema=None) as batch_op:
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
